package com.freelancerMilestoneRiskPredictor.MilestoneRiskPredictor.Dtos;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;

@Schema(description = "Calculated project tracking breakdown and early-warning strategy generated by Gemini AI")
public class MilestoneRiskPredictResponse {
    @Schema(description = "Aggregated systemic milestone risk indicator (0 to 100 percentage layout)", example = "72")
    private int riskScore;

    @Schema(description = "Severity prioritization tier assigned to the active workspace", allowableValues = {"LOW", "MEDIUM", "HIGH", "CRITICAL"}, example = "HIGH")
    private String riskLevel;

    @Schema(description = "Primary bottleneck markers parsed from matching time-elapsed versus completion metrics")
    private List<String> primaryRiskFactors;

    @Schema(description = "Strategic defensive operational step suggested for the contractor", example = "Request 50% upfront before continuing work on the next segment")
    private String recommendation;

    @Schema(description = "Immediate communication escalation template advice to prevent operational friction", example = "Send progress update to client today")
    private String escalationAdvice;

    // CRITICAL: Explicit No-Args Default Constructor for Jackson Mapping
    public MilestoneRiskPredictResponse() {}

    // Parameterized Constructor
    public MilestoneRiskPredictResponse(int riskScore, String riskLevel, List<String> primaryRiskFactors,
                                   String recommendation, String escalationAdvice) {
        this.riskScore = riskScore;
        this.riskLevel = riskLevel;
        this.primaryRiskFactors = primaryRiskFactors;
        this.recommendation = recommendation;
        this.escalationAdvice = escalationAdvice;
    }

    // Getters and Setters
    public int getRiskScore() { return riskScore; }
    public void setRiskScore(int riskScore) { this.riskScore = riskScore; }

    public String getRiskLevel() { return riskLevel; }
    public void setRiskLevel(String riskLevel) { this.riskLevel = riskLevel; }

    public List<String> getPrimaryRiskFactors() { return primaryRiskFactors; }
    public void setPrimaryRiskFactors(List<String> primaryRiskFactors) { this.primaryRiskFactors = primaryRiskFactors; }

    public String getRecommendation() { return recommendation; }
    public void setRecommendation(String recommendation) { this.recommendation = recommendation; }

    public String getEscalationAdvice() { return escalationAdvice; }
    public void setEscalationAdvice(String escalationAdvice) { this.escalationAdvice = escalationAdvice; }
}
