package com.freelancerSmartInvoiceDisputeAnalyser.SmartInvoiceDisputeAnalyser.Dtos;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;

@Schema(description = "The complete legal and negotiation assessment generated by Gemini AI")
public class DisputeResponseDto {
    @Schema(description = "Identified root bottleneck causing the breakdown in communication", example = "Responsive design expectation mismatch")
    private String coreIssue;

    @Schema(description = "Calculated validity score of client's claim. Scale 1-10 (10 = absolute contract breach, 1 = malicious excuse)", example = "7")
    private int disputeValidity;

    @Schema(description = "Assessment of developer's fault level based on deliverables list", allowableValues = {"NONE", "PARTIAL", "FULL"}, example = "PARTIAL")
    private String freelancerLiability;

    @Schema(description = "Step-by-step counter-tactics to resolve issues calmly while protecting revenue", example = "Prioritize addressing the objective, verifiable issue of mobile responsiveness first...")
    private String negotiationStrategy;

    @Schema(description = "Immediate direct operational action step suggested for the freelancer", example = "Immediately and thoroughly test the website's responsiveness across a range of devices.")
    private String recommendedAction;

    @Schema(description = "Hidden client risks, aggressive strategies, or subjective requests flagged outside original contractual agreements")
    private List<String> redFlags;

    @Schema(description = "A pre-written, professionally drafted email/message template ready to be sent to the client", example = "Thank you for your feedback regarding the website. I understand your concerns...")
    private String suggestionsResponse;
    public DisputeResponseDto() {
    }
    public DisputeResponseDto(int disputeValidity,
                              String coreIssue,
                              String freelancerLiability,
                              String suggestionsResponse,
                              String negotiationStrategy,
                              List<String> redFlags,
                              String recommendedAction) {
        this.disputeValidity = disputeValidity;
        this.coreIssue = coreIssue;
        this.freelancerLiability = freelancerLiability;
        this.suggestionsResponse = suggestionsResponse;
        this.negotiationStrategy = negotiationStrategy;
        this.redFlags = redFlags;
        this.recommendedAction = recommendedAction;
    }

    public int getDisputeValidity() {
        return disputeValidity;
    }

    public void setDisputeValidity(int disputeValidity) {
        this.disputeValidity = disputeValidity;
    }

    public String getCoreIssue() {
        return coreIssue;
    }

    public void setCoreIssue(String coreIssue) {
        this.coreIssue = coreIssue;
    }

    public String getFreelancerLiability() {
        return freelancerLiability;
    }

    public void setFreelancerLiability(String freelancerLiability) {
        this.freelancerLiability = freelancerLiability;
    }

    public String getSuggestionsResponse() {
        return suggestionsResponse;
    }

    public void setSuggestionsResponse(String suggestionsResponse) {
        this.suggestionsResponse = suggestionsResponse;
    }

    public String getNegotiationStrategy() {
        return negotiationStrategy;
    }

    public void setNegotiationStrategy(String negotiationStrategy) {
        this.negotiationStrategy = negotiationStrategy;
    }

    public List<String> getRedFlags() {
        return redFlags;
    }

    public void setRedFlags(List<String> redFlags) {
        this.redFlags = redFlags;
    }

    public String getRecommendedAction() {
        return recommendedAction;
    }

    public void setRecommendedAction(String recommendedAction) {
        this.recommendedAction = recommendedAction;
    }



}
