networks:
  AiFreelancerAssitant:
    driver: bridge

services: 
  SmartProposal:
    image: zico7/ai_freelancer_assistant:smart_proposal 
    build: 
      context: ./SmartProposal/SmartProposal
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    env_file:
      - ./.env  
    networks:
      - AiFreelancerAssitant
  MileStoneRiskPredictor:
    image: zico7/ai_freelancer_assistant:milestone_risk_predictor 
    build: 
      context: ./MilestoneRiskPredictor/MilestoneRiskPredictor
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ./.env  
    networks:
      - AiFreelancerAssitant
  SmartInvoiceDisputeAnalyser:
    image: zico7/ai_freelancer_assistant:smart_invoice_dispute_analyser 
    build: 
      context: ./SmartInvoiceDisputeAnalyser/SmartInvoiceDisputeAnalyser
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - ./.env  
    networks:
      - AiFreelancerAssitant
