spring.application.name=AiFreelanceAssistantGateway
spring.config.import=optional:file:.env[.properties]
server.port=${GATEWAY_ANALYSER_SERVICE_PORT}
spring.cloud.gateway.discovery.locator.enabled=true