apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart_invoice_dispute_analyser-deployment
  namespace: AiFreelancerAssistant
  labels:
    app: smart_invoice_dispute_analyser
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smart_invoice_dispute_analyser
  template:
    metadata:
      labels:
        app: smart_invoice_dispute_analyser
    spec:
      containers:
        - name: smart_invoice_dispute_analyser
          image: 'zico7/ai_freelancer_assistant:smart_invoice_dispute_analyser'
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: smart_invoice_dispute_analyser-service
  namespace: AiFreelancerAssistant
spec:
  selector:
    app: smart_invoice_dispute_analyser
  ports:
  - port: 8083
    targetPort: 8083