apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart_proposal-deployment
  namespace: AiFreelancerAssistant
  labels:
    app: smart_proposal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smart_proposal
  template:
    metadata:
      labels:
        app: smart_proposal
    spec:
      containers:
        - name: smart_proposal
          image: 'zico7/ai_freelancer_assistant:smart_proposal'
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: smart_proposal-service
  namespace: AiFreelancerAssistant
spec:
  selector:
    app: smart_proposal
  ports:
  - port: 8084
    targetPort: 8084