spring.application.name=MilestoneRiskPredictor
spring.config.import=optional:file:.env[.properties]
spring.ai.google.genai.api-key=${GEMINI_AI_STUDIO_KEY}
spring.ai.google.genai.chat.options.model=${GEMINI_MODEL}
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
server.port=${RISK_PREDICT_SERVICE_PORT}
